# Generated by Django 5.1.5 on 2025-02-14 11:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_title', models.CharField(max_length=64)),
                ('game_genre', models.CharField(max_length=64)),
                ('game_category', models.CharField(choices=[('RPG', 'RPG'), ('Fighting', 'Fighting'), ('Shooter', 'Shooter'), ('Action', 'Action'), ('Racing', 'Racing'), ('Adventure', 'Adventure'), ('Sports', 'Sports')], max_length=10)),
                ('game_platform', models.CharField(max_length=64)),
                ('game_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('game_quantity', models.IntegerField()),
                ('game_discount_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('game_description', models.TextField()),
                ('image_url', models.ImageField(default='game-images/default.png', upload_to='game-images/')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('street_address', models.CharField(max_length=200)),
                ('apartment_address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid postcode.', regex='^[A-Z0-9 ]+$')])),
                ('save_info', models.BooleanField(default=False)),
                ('default', models.BooleanField(default=False)),
                ('use_default', models.BooleanField(default=False)),
                ('payment_option', models.CharField(choices=[('S', 'Stripe'), ('P', 'Paypal')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamestore.games')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='gamestore.orderitem')),
            ],
        ),
    ]
