# Generated by Django 5.1.5 on 2025-01-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_price',
            field=models.IntegerField(),
        ),
    ]
