# Generated by Django 5.1.5 on 2025-02-11 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamestore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_title', models.CharField(max_length=64)),
                ('game_genre', models.CharField(max_length=64)),
                ('game_category', models.CharField(choices=[('RPG', 'RPG'), ('Fighting', 'Fighting'), ('Shooter', 'Shooter'), ('Action', 'Action'), ('Racing', 'Racing'), ('Adventure', 'Adventure'), ('Sports', 'Sports')], max_length=10)),
                ('game_platform', models.CharField(max_length=64)),
                ('game_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('game_quantity', models.IntegerField()),
                ('game_discount_price', models.IntegerField(blank=True, null=True)),
                ('game_description', models.TextField()),
                ('image_url', models.CharField(default='images/game-images/default.jpg', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamestore.games')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='gamestore.orderitem')),
            ],
        ),
    ]
