# Generated by Django 5.1.5 on 2025-02-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0002_alter_address_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='image_url',
            field=models.ImageField(blank=True, default='game-images/default.png', null=True, upload_to='game-images/'),
        ),
    ]
