# Generated by Django 5.1.4 on 2025-02-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0002_alter_games_game_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
