# Generated by Django 5.1.5 on 2025-02-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0003_alter_games_game_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='image_url',
            field=models.ImageField(default='game-images/default.jpg', upload_to='game-images/'),
        ),
    ]
