# Generated by Django 5.1.5 on 2025-02-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0003_alter_games_game_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='image_url',
            field=models.CharField(default='images/game-images/default.jpg', max_length=255),
        ),
    ]
