# Generated by Django 5.1.5 on 2025-02-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0005_alter_games_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
