# Generated by Django 4.2.19 on 2025-03-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0006_alter_games_game_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='image_url',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
