# Generated by Django 5.1.5 on 2025-02-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0007_alter_games_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='image_url',
            field=models.ImageField(default='game-images/default.jpg', upload_to='game-images/'),
        ),
    ]
