# Generated by Django 5.1.5 on 2025-02-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0008_alter_games_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='image_url',
            field=models.ImageField(default='game-images/default.png', upload_to='game-images/'),
        ),
    ]
